Use os.makedirs to create intermediate directories
OwnCA/ownca pull request #58
Opened 2022-01-05 21:31 UTC by lawndoc

This is just a simple change that lets people specify any number of new directories in the path for the CA storage.

I had to remove test__create_ownca_dir_case_exceptions because none of the exceptions were raised after using makedirs.

2022-01-05 21:36 UTC, lawndoc commented
Also, this may have happened because I have contributed before, but the test/build actions kicked off as soon as I submitted my PR. You'll want to make sure that first time contributors require approval to kick off automated tests, or they could run arbitrary code in the CI environment and steal repo secrets (if there are any).

2022-01-06 09:09 UTC, kairoaraujo commented
Thank you for the PR.

> Also, this may have happened because I have contributed before, but the test/build actions kicked off as soon as I submitted my PR. You'll want to make sure that first time contributors require approval to kick off automated tests, or they could run arbitrary code in the CI environment and steal repo secrets (if there are any).

The test/build actions are started only upon approval. Your case is because you have contributed before, as you mentioned.

2022-01-06 09:20 UTC, kairoaraujo requested changes

2022-01-06 14:37 UTC, lawndoc commented on tests/unit/ownca/test_utils.py
> -    mock_os.mkdir.side_effect = exceptions
Oops I had missed that, thanks. Adding a new commit now.

2022-01-06 21:40 UTC, lawndoc commented
I think I made the changes you wanted. Let me know if there's anything else that needs taken care of.

2022-01-08 21:28 UTC, kairoaraujo approved these changes

2022-01-08 21:29 UTC, merged